CREATE DATABASE IF NOT EXISTS LOGINDB;

USE LOGINDB;

CREATE TABLE IF NOT EXISTS USERS(
	Name varchar(100) NOT NULL PRIMARY KEY, INDEX(Name), UNIQUE(Name),
	Email varchar(100) NOT NULL, INDEX(Email), UNIQUE(Email),
	Hash varchar(100) NOT NULL,
	Salt varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS(
	Name varchar(100) NOT NULL PRIMARY KEY, INDEX(Name), UNIQUE(Name)
);

CREATE TABLE IF NOT EXISTS TEAM_MEMBERSHIP(
	TName varchar(100) NOT NULL, INDEX(TName),
	UName varchar(100) NOT NULL, INDEX(UName),
	FOREIGN KEY (TName) REFERENCES TEAMS(Name) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (UName) REFERENCES USERS(Name) ON UPDATE CASCADE ON DELETE CASCADE
);
