CREATE DATABASE IF NOT EXISTS LOGINDB;

USE LOGINDB;

CREATE TABLE IF NOT EXISTS USERS(
	UID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name varchar(100) NOT NULL, INDEX(Name), UNIQUE(Name),
	Email varchar(100) NOT NULL, INDEX(Email), UNIQUE(Email),
	Hash varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS(
	TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name varchar(100) NOT NULL, INDEX(Name), UNIQUE(Name)
);

CREATE TABLE IF NOT EXISTS TEAM_MEMBERSHIP(
	TID INT NOT NULL, INDEX(TID),
	UID INT NOT NULL, INDEX(UID),

	FOREIGN KEY (TID) REFERENCES TEAMS(TID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (UID) REFERENCES USERS(UID) ON UPDATE CASCADE ON DELETE CASCADE
);
